In [2]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

#import modules

In [3]:
#import data
lfs_jan = pd.read_table("Hands on #1\lfs_01_2015.tab", sep= '\t')
lfs_jan

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SPED7689,SPED1990,SP_SOC80,SP_NOCS01,SP_UHRSM,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT
0,1,2015,1,1,11,4,12,NaN,2,1,...,NaN,3.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,44
1,2,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,84
2,3,2015,1,1,35,4,7,NaN,1,1,...,NaN,5.0,NaN,5.0,4.0,4.0,2.0,3.0,NaN,195
3,4,2015,1,4,59,4,3,5.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110
4,5,2015,1,1,24,4,4,NaN,1,2,...,NaN,5.0,NaN,10.0,4.0,4.0,1.0,1.0,NaN,101
5,6,2015,1,1,46,4,7,NaN,2,1,...,NaN,4.0,NaN,6.0,5.0,5.0,2.0,4.0,1.0,60
6,7,2015,1,6,35,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,235
7,8,2015,1,1,59,3,9,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415
8,9,2015,1,1,47,4,12,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,106
9,10,2015,1,1,35,4,11,NaN,2,1,...,NaN,2.0,NaN,23.0,NaN,NaN,1.0,NaN,NaN,204
10,11,2015,1,1,59,3,2,4.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117
11,12,2015,1,1,59,3,2,4.0,2,2,...,NaN,5.0,NaN,6.0,5.0,5.0,2.0,NaN,NaN,714
12,13,2015,1,1,35,4,8,NaN,2,1,...,NaN,2.0,NaN,24.0,5.0,5.0,2.0,NaN,NaN,202
13,14,2015,1,6,10,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84
14,15,2015,1,1,48,4,5,NaN,2,1,...,NaN,5.0,NaN,6.0,5.0,5.0,1.0,2.0,NaN,521
15,16,2015,1,6,12,4,11,NaN,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138
16,17,2015,1,1,24,4,3,5.0,2,2,...,NaN,4.0,NaN,2.0,7.0,7.0,5.0,NaN,NaN,127
17,18,2015,1,2,59,4,3,6.0,2,1,...,NaN,1.0,NaN,21.0,5.0,5.0,2.0,1.0,NaN,112
18,19,2015,1,1,35,4,8,NaN,1,1,...,NaN,4.0,NaN,14.0,1.0,3.0,2.0,4.0,1.0,216
19,20,2015,1,6,24,1,11,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,772
20,21,2015,1,1,48,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,559
21,22,2015,1,1,35,4,8,NaN,2,2,...,NaN,4.0,NaN,9.0,5.0,5.0,1.0,NaN,NaN,194
22,23,2015,1,1,47,4,6,NaN,2,1,...,NaN,4.0,NaN,17.0,5.0,5.0,2.0,5.0,1.0,164
23,24,2015,1,1,48,4,4,NaN,2,1,...,NaN,4.0,NaN,20.0,5.0,5.0,2.0,2.0,NaN,550
24,25,2015,1,1,35,4,8,NaN,1,1,...,NaN,4.0,NaN,2.0,4.0,4.0,1.0,NaN,NaN,267
25,26,2015,1,1,46,4,4,NaN,2,1,...,NaN,3.0,NaN,3.0,2.0,2.0,2.0,1.0,NaN,166
26,27,2015,1,1,35,4,7,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227
27,28,2015,1,1,12,4,9,NaN,2,1,...,NaN,2.0,NaN,21.0,4.0,4.0,2.0,NaN,NaN,117
28,29,2015,1,6,46,4,12,NaN,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
29,30,2015,1,6,35,4,1,1.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102732,102733,2015,1,6,48,4,12,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480
102733,102734,2015,1,1,35,4,3,5.0,2,2,...,NaN,3.0,NaN,19.0,7.0,7.0,2.0,NaN,NaN,466
102734,102735,2015,1,1,35,4,6,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301
102735,102736,2015,1,1,35,4,3,6.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152
102736,102737,2015,1,1,35,4,3,6.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,784
102737,102738,2015,1,1,24,1,6,NaN,2,1,...,NaN,4.0,NaN,17.0,7.0,7.0,4.0,4.0,1.0,588
102738,102739,2015,1,1,24,4,7,NaN,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
102739,102740,2015,1,1,12,4,5,NaN,1,1,...,NaN,5.0,NaN,4.0,5.0,5.0,2.0,2.0,NaN,135
102740,102741,2015,1,1,10,4,10,NaN,1,1,...,NaN,4.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,109
102741,102742,2015,1,1,46,4,6,NaN,1,1,...,NaN,4.0,NaN,9.0,1.0,1.0,2.0,3.0,NaN,67
102742,102743,2015,1,1,46,4,4,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150
102743,102744,2015,1,1,24,4,8,NaN,1,2,...,NaN,5.0,NaN,NaN,NaN,NaN,0.0,5.0,1.0,523
102744,102745,2015,1,6,35,4,11,NaN,1,2,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,213
102745,102746,2015,1,4,24,1,9,NaN,1,1,...,NaN,3.0,NaN,8.0,4.0,4.0,1.0,1.0,NaN,697
102746,102747,2015,1,1,59,4,9,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450
102747,102748,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,594
102748,102749,2015,1,1,35,4,3,6.0,1,2,...,NaN,1.0,NaN,4.0,3.0,3.0,2.0,NaN,NaN,308
102749,102750,2015,1,1,24,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77
102750,102751,2015,1,1,12,4,7,NaN,1,2,...,NaN,4.0,NaN,13.0,2.0,2.0,2.0,6.0,NaN,112
102751,102752,2015,1,1,46,4,9,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
102752,102753,2015,1,1,48,4,9,NaN,1,1,...,NaN,2.0,NaN,4.0,5.0,5.0,2.0,NaN,NaN,490
102753,102754,2015,1,1,35,4,8,NaN,2,1,...,NaN,4.0,NaN,20.0,5.0,5.0,2.0,NaN,NaN,161
102754,102755,2015,1,6,59,4,10,NaN,2,1,...,NaN,2.0,NaN,12.0,7.0,7.0,6.0,NaN,NaN,136
102755,102756,2015,1,6,13,4,11,NaN,1,1,...,NaN,4.0,NaN,5.0,5.0,5.0,2.0,NaN,NaN,143
102756,102757,2015,1,1,46,4,11,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79
102757,102758,2015,1,6,10,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122
102758,102759,2015,1,1,59,4,9,NaN,2,1,...,NaN,1.0,NaN,2.0,5.0,5.0,4.0,NaN,NaN,50
102759,102760,2015,1,2,12,4,9,NaN,1,1,...,NaN,5.0,NaN,NaN,NaN,NaN,0.0,1.0,1.0,171
102760,102761,2015,1,1,24,4,8,NaN,1,1,...,NaN,4.0,NaN,3.0,5.0,5.0,2.0,6.0,NaN,585
102761,102762,2015,1,4,12,4,8,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168

In [4]:
list(lfs_jan)

['REC_NUM',
 'SURVYEAR',
 'SURVMNTH',
 'LFSSTAT',
 'PROV',
 'CMA',
 'AGE_12',
 'AGE_6',
 'SEX',
 'MARSTAT',
 'ED76to89',
 'EDUC90',
 'MJH',
 'EVERWORK',
 'FTPTLAST',
 'COWMAIN',
 'NAICS_18',
 'NAICS_43',
 'SOC80_49',
 'SOC80_21',
 'NOCS_01_25',
 'NOCS_01_47',
 'YABSENT',
 'WKSAWAY',
 'PAYAWAY',
 'UHRSMAIN',
 'AHRSMAIN',
 'FTPTMAIN',
 'UTOTHRS',
 'ATOTHRS',
 'HRSAWAY',
 'YAWAY',
 'PAIDOT',
 'UNPAIDOT',
 'XTRAHRS',
 'WHYPTOLD',
 'WHYPTNEW',
 'TENURE',
 'PREVTEN',
 'HRLYEARN',
 'UNION',
 'PERMTEMP',
 'ESTSIZE',
 'FIRMSIZE',
 'DURUNEMP',
 'FLOWUNEM',
 'UNEMFTPT',
 'WHYLEFTO',
 'WHYLEFTN',
 'DURJLESS',
 'AVAILABL',
 'LKPUBAG',
 'LKEMPLOY',
 'LKRELS',
 'LKATADS',
 'LKANSADS',
 'LKOTHER',
 'PRIORACT',
 'YNOLKOLD',
 'YNOLOOK',
 'TLOLOOK',
 'SCHOOLN',
 'RELREFN',
 'EFAMTYPE',
 'EFAMSIZE',
 'EFAMEMPL',
 'EFAMUNEM',
 'SP_AGE',
 'SP_LFSST',
 'SPED7689',
 'SPED1990',
 'SP_SOC80',
 'SP_NOCS01',
 'SP_UHRSM',
 'SP_UHRST',
 'SP_COWM',
 'AGYOWNKN',
 'SCH1624',
 'FWEIGHT']

In [5]:
lfs_jan['highestDegree']=6
degree_map = {
    0:0, 
    1:1,
    2:3,
    3:3,
    4:4,
    5:5
    }
lfs_jan['highestDegree']= lfs_jan['EDUC90'].map(degree_map)

In [6]:
lfs_jan['highestDegree'].describe()

count    96606.000000
mean         3.142341
std          1.432409
min          0.000000
25%          3.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: highestDegree, dtype: float64

In [7]:
lfs_jan['highestDegree']=lfs_jan['highestDegree'].fillna(6)
lfs_jan['highestDegree'].describe()

count    102762.000000
mean          3.313530
std           1.545568
min           0.000000
25%           3.000000
50%           4.000000
75%           4.000000
max           6.000000
Name: highestDegree, dtype: float64

In [8]:
lfs_feb = pd.read_table("Hands on #1\lfs_02_2015.tab", sep= '\t')

In [9]:
lfs_feb['highestDegree']= lfs_feb['EDUC90'].map(degree_map)

In [10]:
lfs_joined = lfs_jan.append(lfs_feb)

In [11]:
lfs_joined.describe()

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SPED1990,SP_SOC80,SP_NOCS01,SP_UHRSM,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT,highestDegree
count,203436.000000,203436.0,203436.000000,203436.000000,203436.000000,203436.000000,203436.000000,44320.000000,203436.000000,203436.000000,...,115960.000000,0.0,81248.000000,73984.000000,73984.000000,115960.000000,57180.000000,16536.0,203436.000000,197337.000000
mean,50864.857636,2015.0,1.494868,3.014250,35.248938,3.718152,6.934019,3.595352,1.514658,2.854328,...,3.284443,NaN,11.791946,4.377852,4.460600,1.567221,3.264096,1.0,286.576024,3.232835
std,29372.807274,0.0,0.499975,2.354163,14.619804,0.756413,3.504879,1.691518,0.499786,2.158561,...,1.501150,NaN,7.097746,1.496881,1.515694,1.518349,1.746950,0.0,255.522164,1.495254
min,1.000000,2015.0,1.000000,1.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,NaN,1.000000,1.000000,1.000000,0.000000,1.000000,1.0,1.000000,0.000000
25%,25430.000000,2015.0,1.000000,1.000000,24.000000,4.000000,4.000000,2.000000,1.000000,1.000000,...,2.000000,NaN,5.000000,4.000000,4.000000,0.000000,2.000000,1.0,114.000000,3.000000
50%,50859.500000,2015.0,1.000000,1.000000,35.000000,4.000000,7.000000,4.000000,2.000000,2.000000,...,4.000000,NaN,10.000000,5.000000,5.000000,2.000000,3.000000,1.0,178.000000,4.000000
75%,76289.000000,2015.0,2.000000,6.000000,47.000000,4.000000,10.000000,5.000000,2.000000,6.000000,...,4.000000,NaN,18.000000,5.000000,5.000000,2.000000,5.000000,1.0,390.000000,4.000000
max,102762.000000,2015.0,2.000000,6.000000,59.000000,4.000000,12.000000,6.000000,2.000000,6.000000,...,5.000000,NaN,25.000000,7.000000,7.000000,7.000000,6.000000,1.0,2139.000000,6.000000

In [12]:
prov_pop = pd.read_stata("Hands on #1\province_pop.dta")

In [13]:
prov_pop.columns = [str.upper(i) for i in (prov_pop.columns)]

In [14]:
prov_pop.columns

Index(['PROVINCE_NAME', 'PROV', 'MONTH_NAME', 'SURVMNTH', 'SURVYEAR', 'POP'], dtype='object')

In [15]:

prov_pop['SURVMNTH']= prov_pop['MONTH_NAME'].map({'Jan-15':1,'Feb-15':2})
#merged = pd.merge(lfs_merged)

In [16]:
prov_pop

,PROVINCE_NAME,PROV,MONTH_NAME,SURVMNTH,SURVYEAR,POP
0,Prince Edward Island (map),11,Jan-15,1,2015,120.800003
1,Prince Edward Island (map),11,Feb-15,2,2015,120.699997
2,Nova Scotia (map),12,Jan-15,1,2015,784.099976
3,Nova Scotia (map),12,Feb-15,2,2015,784.200012
4,New Brunswick (map),13,Jan-15,1,2015,622.000000
5,New Brunswick (map),13,Feb-15,2,2015,622.099976
6,Quebec (map),24,Jan-15,1,2015,6825.000000
7,Quebec (map),24,Feb-15,2,2015,6827.500000
8,Ontario (map),35,Jan-15,1,2015,11329.099609
9,Ontario (map),35,Feb-15,2,2015,11338.099609
10,Manitoba (map),46,Jan-15,1,2015,982.500000
11,Manitoba (map),46,Feb-15,2,2015,983.099976
12,Saskatchewan (map),47,Jan-15,1,2015,857.799988
13,Saskatchewan (map),47,Feb-15,2,2015,858.400024
14,Alberta (map),48,Jan-15,1,2015,3323.000000
15,Alberta (map),48,Feb-15,2,2015,3327.800049
16,British Columbia (map),59,Jan-15,1,2015,3851.600098
17,British Columbia (map),59,Feb-15,2,2015,3855.500000

In [17]:
merged = pd.merge(lfs_joined,prov_pop, on=['PROV','SURVMNTH'])

In [18]:
merged

,REC_NUM,SURVYEAR_x,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT,highestDegree,PROVINCE_NAME,MONTH_NAME,SURVYEAR_y,POP
0,1,2015,1,1,11,4,12,NaN,2,1,...,NaN,0.0,NaN,NaN,44,5.0,Prince Edward Island (map),Jan-15,2015,120.800003
1,83,2015,1,1,11,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,39,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
2,208,2015,1,1,11,4,4,NaN,2,1,...,4.0,2.0,NaN,NaN,23,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
3,223,2015,1,1,11,4,3,6.0,2,2,...,4.0,1.0,1.0,NaN,48,5.0,Prince Edward Island (map),Jan-15,2015,120.800003
4,258,2015,1,6,11,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,59,0.0,Prince Edward Island (map),Jan-15,2015,120.800003
5,279,2015,1,6,11,4,7,NaN,2,1,...,7.0,3.0,3.0,NaN,55,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
6,362,2015,1,6,11,4,10,NaN,2,1,...,NaN,0.0,6.0,1.0,56,5.0,Prince Edward Island (map),Jan-15,2015,120.800003
7,433,2015,1,1,11,4,11,NaN,1,1,...,4.0,1.0,6.0,1.0,51,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
8,503,2015,1,1,11,4,4,NaN,2,1,...,6.0,2.0,2.0,NaN,56,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
9,523,2015,1,1,11,4,7,NaN,2,5,...,NaN,NaN,NaN,NaN,14,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
10,525,2015,1,4,11,4,10,NaN,1,1,...,NaN,NaN,NaN,NaN,41,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
11,543,2015,1,1,11,4,11,NaN,1,1,...,NaN,NaN,NaN,NaN,29,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
12,546,2015,1,6,11,4,11,NaN,2,1,...,NaN,0.0,NaN,NaN,60,0.0,Prince Edward Island (map),Jan-15,2015,120.800003
13,666,2015,1,3,11,4,10,NaN,2,3,...,NaN,NaN,NaN,NaN,56,0.0,Prince Edward Island (map),Jan-15,2015,120.800003
14,683,2015,1,1,11,4,4,NaN,2,2,...,5.0,2.0,4.0,NaN,49,5.0,Prince Edward Island (map),Jan-15,2015,120.800003
15,710,2015,1,1,11,4,1,2.0,1,6,...,NaN,NaN,NaN,NaN,53,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
16,750,2015,1,6,11,4,12,NaN,2,1,...,NaN,0.0,NaN,NaN,40,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
17,769,2015,1,1,11,4,4,NaN,2,2,...,7.0,2.0,NaN,NaN,58,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
18,810,2015,1,3,11,4,6,NaN,1,1,...,5.0,1.0,3.0,NaN,52,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
19,857,2015,1,1,11,4,9,NaN,1,1,...,4.0,2.0,4.0,NaN,39,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
20,973,2015,1,1,11,4,2,3.0,2,6,...,NaN,NaN,NaN,NaN,103,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
21,1038,2015,1,4,11,4,2,3.0,2,4,...,NaN,NaN,NaN,NaN,60,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
22,1043,2015,1,1,11,4,8,NaN,2,4,...,NaN,NaN,6.0,1.0,60,6.0,Prince Edward Island (map),Jan-15,2015,120.800003
23,1083,2015,1,1,11,4,5,NaN,2,1,...,6.0,2.0,3.0,NaN,53,5.0,Prince Edward Island (map),Jan-15,2015,120.800003
24,1088,2015,1,1,11,4,9,NaN,2,1,...,6.0,2.0,5.0,1.0,47,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
25,1097,2015,1,6,11,4,7,NaN,1,2,...,5.0,2.0,NaN,NaN,47,1.0,Prince Edward Island (map),Jan-15,2015,120.800003
26,1106,2015,1,1,11,4,10,NaN,2,4,...,NaN,NaN,NaN,NaN,39,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
27,1154,2015,1,3,11,4,4,NaN,1,6,...,NaN,NaN,3.0,NaN,38,3.0,Prince Edward Island (map),Jan-15,2015,120.800003
28,1226,2015,1,1,11,4,10,NaN,2,4,...,NaN,NaN,NaN,NaN,43,5.0,Prince Edward Island (map),Jan-15,2015,120.800003
29,1292,2015,1,1,11,4,10,NaN,2,1,...,NaN,0.0,NaN,NaN,30,4.0,Prince Edward Island (map),Jan-15,2015,120.800003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195938,100142,2015,2,1,13,4,9,NaN,2,1,...,NaN,0.0,NaN,NaN,88,5.0,New Brunswick (map),Feb-15,2015,622.099976
195939,100166,2015,2,6,13,4,10,NaN,1,1,...,4.0,2.0,NaN,NaN,115,1.0,New Brunswick (map),Feb-15,2015,622.099976
195940,100188,2015,2,1,13,4,9,NaN,1,1,...,3.0,2.0,NaN,NaN,109,4.0,New Brunswick (map),Feb-15,2015,622.099976
195941,100190,2015,2,1,13,4,5,NaN,2,1,...,5.0,2.0,3.0,NaN,155,5.0,New Brunswick (map),Feb-15,2015,622.099976
195942,100199,2015,2,6,13,4,11,NaN,2,5,...,NaN,NaN,NaN,NaN,233,0.0,New Brunswick (map),Feb-15,2015,622.099976
195943,100211,2015,2,1,13,4,8,NaN,1,4,...,NaN,NaN,NaN,NaN,190,3.0,New Brunswick (map),Feb-15,2015,622.099976
195944,100216,2015,2,1,13,4,2,3.0,1,6,...,NaN,NaN,NaN,NaN,148,4.0,New Brunswick (map),Feb-15,2015,622.099976
195945,100225,2015,2,1,13,4,7,NaN,2,1,...,NaN,NaN,3.0,NaN,147,4.0,New Brunswick (map),Feb-15,2015,622.099976
195946,100227,2015,2,1,13,4,7,NaN,2,1,...,3.0,1.0,4.0,1.0,76,4.0,New Brunswick (map),Feb-15,2015,622.099976
195947,100284,2015,2,6,13,4,12,NaN,2,5,...,NaN,NaN,NaN,NaN,78,1.0,New Brunswick (map),Feb-15,2015,622.099976
195948,100285,2015,2,1,13,4,8,NaN,2,6,...,NaN,NaN,NaN,NaN,102,3.0,New Brunswick (map),Feb-15,2015,622.099976
195949,100288,2015,2,1,13,4,10,NaN,1,2,...,5.0,1.0,NaN,NaN,105,4.0,New Brunswick (map),Feb-15,2015,622.099976
195950,100290,2015,2,1,13,4,4,NaN,1,2,...,5.0,2.0,NaN,NaN,128,3.0,New Brunswick (map),Feb-15,2015,622.099976
195951,100303,2015,2,1,13,4,7,NaN,2,1,...,7.0,3.0,6.0,NaN,183,3.0,New Brunswick (map),Feb-15,2015,622.099976
195952,100305,2015,2,6,13,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,97,0.0,New Brunswick (map),Feb-15,2015,622.099976
195953,100341,2015,2,6,13,4,11,NaN,1,1,...,NaN,1.0,NaN,NaN,95,1.0,New Brunswick (map),Feb-15,2015,622.099976
195954,100366,2015,2,1,13,4,6,NaN,2,2,...,NaN,0.0,3.0,1.0,160,5.0,New Brunswick (map),Feb-15,2015,622.099976
195955,100372,2015,2,6,13,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,122,1.0,New Brunswick (map),Feb-15,2015,622.099976
195956,100409,2015,2,6,13,4,12,NaN,1,1,...,NaN,1.0,NaN,NaN,70,5.0,New Brunswick (map),Feb-15,2015,622.099976
195957,100423,2015,2,1,13,4,2,4.0,2,2,...,6.0,2.0,NaN,NaN,84,5.0,New Brunswick (map),Feb-15,2015,622.099976
195958,100449,2015,2,6,13,4,12,NaN,2,1,...,NaN,0.0,NaN,NaN,112,4.0,New Brunswick (map),Feb-15,2015,622.099976
195959,100461,2015,2,1,13,4,5,NaN,1,1,...,4.0,1.0,2.0,NaN,88,3.0,New Brunswick (map),Feb-15,2015,622.099976
195960,100483,2015,2,1,13,4,6,NaN,1,1,...,6.0,3.0,3.0,NaN,134,5.0,New Brunswick (map),Feb-15,2015,622.099976
195961,100520,2015,2,1,13,4,5,NaN,2,1,...,5.0,1.0,3.0,NaN,100,5.0,New Brunswick (map),Feb-15,2015,622.099976
195962,100531,2015,2,1,13,4,5,NaN,2,1,...,5.0,1.0,3.0,NaN,140,4.0,New Brunswick (map),Feb-15,2015,622.099976
195963,100534,2015,2,4,13,4,1,2.0,1,6,...,NaN,NaN,NaN,NaN,173,3.0,New Brunswick (map),Feb-15,2015,622.099976
195964,100541,2015,2,6,13,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,114,NaN,New Brunswick (map),Feb-15,2015,622.099976
195965,100601,2015,2,6,13,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,84,1.0,New Brunswick (map),Feb-15,2015,622.099976
195966,100635,2015,2,1,13,4,8,NaN,2,5,...,NaN,NaN,6.0,1.0,123,4.0,New Brunswick (map),Feb-15,2015,622.099976
195967,100668,2015,2,6,13,4,11,NaN,2,1,...,NaN,0.0,NaN,NaN,101,5.0,New Brunswick (map),Feb-15,2015,622.099976

## Regressions

In [19]:
import statsmodels.api as sm

In [20]:
merged['isFemale']= merged['SEX'].map({1:0,2:1})

In [21]:
y = merged['HRLYEARN']

In [22]:
x = merged[['AGE_12','PROV','CMA','isFemale','MARSTAT']]

reg1 = sm.OLS(endog=y, exog=x, missing='drop')

In [52]:
results=reg1.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               HRLYEARN   R-squared:                       0.797
Model:                            OLS   Adj. R-squared:                  0.797
Method:                 Least Squares   F-statistic:                 7.683e+04
Date:                Mon, 11 Feb 2019   Prob (F-statistic):               0.00
Time:                        12:34:21   Log-Likelihood:            -3.8479e+05
No. Observations:               97749   AIC:                         7.696e+05
Df Residuals:                   97744   BIC:                         7.696e+05
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
AGE_12         1.4387      0.014    101.938      0.000       1.411       1.466
PROV           0.1805      0.003     67.040      0.000       0.175       0.186
CMA            3.0193      0.036     83.924      0.000       2.949       3.090
isFemale      -2.5379      0.078    -32.412      0.000      -2.691      -2.384
MARSTAT       -0.3238      0.018    -17.638      0.000      -0.360      -0.288
==============================================================================
Omnibus:                    17907.560   Durbin-Watson:                   1.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            36775.256
Skew:                           1.097   Prob(JB):                         0.00
Kurtosis:                       5.054   Cond. No.                         78.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
merged['NOCS_01_47']

0         40.0
1         25.0
2         10.0
3         14.0
4          NaN
5          NaN
6          NaN
7         24.0
8         19.0
9          6.0
10        11.0
11         8.0
12         NaN
13        42.0
14         5.0
15        31.0
16         NaN
17        22.0
18        36.0
19        29.0
20        19.0
21        24.0
22        17.0
23        18.0
24         7.0
25        40.0
26         3.0
27        38.0
28        18.0
29        14.0
          ...
195938    14.0
195939    40.0
195940    45.0
195941    15.0
195942     NaN
195943     4.0
195944    28.0
195945    18.0
195946    15.0
195947     NaN
195948    31.0
195949    36.0
195950    10.0
195951    24.0
195952     NaN
195953     NaN
195954    23.0
195955     NaN
195956     NaN
195957    14.0
195958     NaN
195959     9.0
195960    18.0
195961    16.0
195962    10.0
195963    45.0
195964     NaN
195965     NaN
195966    30.0
195967     NaN
Name: NOCS_01_47, Length: 195968, dtype: float64

In [25]:

print(merged[merged['isFemale']==True]['XTRAHRS'].describe())
print(merged[merged['isFemale']==False]['XTRAHRS'].describe())

count    44909.000000
mean         1.284631
std          3.967877
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         99.000000
Name: XTRAHRS, dtype: float64
count    45571.000000
mean         2.316649
std          5.864695
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         99.000000
Name: XTRAHRS, dtype: float64

In [27]:
merged['postTreatment']=merged['SURVMNTH'].map({1:0,2:1})

In [28]:
merged['postTreatment']

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
         ..
195938    1
195939    1
195940    1
195941    1
195942    1
195943    1
195944    1
195945    1
195946    1
195947    1
195948    1
195949    1
195950    1
195951    1
195952    1
195953    1
195954    1
195955    1
195956    1
195957    1
195958    1
195959    1
195960    1
195961    1
195962    1
195963    1
195964    1
195965    1
195966    1
195967    1
Name: postTreatment, Length: 195968, dtype: int64

In [34]:
merged['treatedGroup']=merged['PROV'].map({35:1})

In [39]:
merged['treatedGroup'].fillna(0,inplace=True)

In [40]:
merged['treatedGroup']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         0.0
10        0.0
11        0.0
12        0.0
13        0.0
14        0.0
15        0.0
16        0.0
17        0.0
18        0.0
19        0.0
20        0.0
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        0.0
29        0.0
         ...
195938    0.0
195939    0.0
195940    0.0
195941    0.0
195942    0.0
195943    0.0
195944    0.0
195945    0.0
195946    0.0
195947    0.0
195948    0.0
195949    0.0
195950    0.0
195951    0.0
195952    0.0
195953    0.0
195954    0.0
195955    0.0
195956    0.0
195957    0.0
195958    0.0
195959    0.0
195960    0.0
195961    0.0
195962    0.0
195963    0.0
195964    0.0
195965    0.0
195966    0.0
195967    0.0
Name: treatedGroup, Length: 195968, dtype: float64

In [49]:
x_2 = merged[['postTreatment','treatedGroup']]
reg_2 = sm.OLS(endog=y, exog=x_2, missing='drop')

In [53]:
results_2=reg_2.fit()
results_2.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                  Results: Ordinary least squares
====================================================================
Model:              OLS              Adj. R-squared:     0.466
Dependent Variable: HRLYEARN         AIC:                864216.5561
Date:               2019-02-11 12:34 BIC:                864235.5364
No. Observations:   97749            Log-Likelihood:     -4.3211e+05
Df Model:           2                F-statistic:        4.265e+04
Df Residuals:       97747            Prob (F-statistic): 0.00
R-squared:          0.466            Scale:              404.76
---------------------------------------------------------------------
                 Coef.   Std.Err.     t      P>|t|    [0.025   0.975]
---------------------------------------------------------------------
postTreatment   20.1589    0.0988  204.1318  0.0000  19.9653  20.3524
treatedGroup    14.9305    0.1285  116.1778  0.0000  14.6786  15.1824
--------------------------------------------------------------------
Omnibus:             2975.449       Durbin-Watson:          0.770
Prob(Omnibus):       0.000          Jarque-Bera (JB):       3374.952
Skew:                0.408          Prob(JB):               0.000
Kurtosis:            3.405          Condition No.:          2
====================================================================

"""