In [3]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

In [34]:
lfs_jan = pd.read_table("Hands on #1\lfs_01_2015.tab", sep= '\t')

In [5]:
lfs_jan

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SPED7689,SPED1990,SP_SOC80,SP_NOCS01,SP_UHRSM,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT
0,1,2015,1,1,11,4,12,NaN,2,1,...,NaN,3.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,44
1,2,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,84
2,3,2015,1,1,35,4,7,NaN,1,1,...,NaN,5.0,NaN,5.0,4.0,4.0,2.0,3.0,NaN,195
3,4,2015,1,4,59,4,3,5.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110
4,5,2015,1,1,24,4,4,NaN,1,2,...,NaN,5.0,NaN,10.0,4.0,4.0,1.0,1.0,NaN,101
5,6,2015,1,1,46,4,7,NaN,2,1,...,NaN,4.0,NaN,6.0,5.0,5.0,2.0,4.0,1.0,60
6,7,2015,1,6,35,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,235
7,8,2015,1,1,59,3,9,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415
8,9,2015,1,1,47,4,12,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,106
9,10,2015,1,1,35,4,11,NaN,2,1,...,NaN,2.0,NaN,23.0,NaN,NaN,1.0,NaN,NaN,204
10,11,2015,1,1,59,3,2,4.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117
11,12,2015,1,1,59,3,2,4.0,2,2,...,NaN,5.0,NaN,6.0,5.0,5.0,2.0,NaN,NaN,714
12,13,2015,1,1,35,4,8,NaN,2,1,...,NaN,2.0,NaN,24.0,5.0,5.0,2.0,NaN,NaN,202
13,14,2015,1,6,10,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84
14,15,2015,1,1,48,4,5,NaN,2,1,...,NaN,5.0,NaN,6.0,5.0,5.0,1.0,2.0,NaN,521
15,16,2015,1,6,12,4,11,NaN,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138
16,17,2015,1,1,24,4,3,5.0,2,2,...,NaN,4.0,NaN,2.0,7.0,7.0,5.0,NaN,NaN,127
17,18,2015,1,2,59,4,3,6.0,2,1,...,NaN,1.0,NaN,21.0,5.0,5.0,2.0,1.0,NaN,112
18,19,2015,1,1,35,4,8,NaN,1,1,...,NaN,4.0,NaN,14.0,1.0,3.0,2.0,4.0,1.0,216
19,20,2015,1,6,24,1,11,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,772
20,21,2015,1,1,48,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,559
21,22,2015,1,1,35,4,8,NaN,2,2,...,NaN,4.0,NaN,9.0,5.0,5.0,1.0,NaN,NaN,194
22,23,2015,1,1,47,4,6,NaN,2,1,...,NaN,4.0,NaN,17.0,5.0,5.0,2.0,5.0,1.0,164
23,24,2015,1,1,48,4,4,NaN,2,1,...,NaN,4.0,NaN,20.0,5.0,5.0,2.0,2.0,NaN,550
24,25,2015,1,1,35,4,8,NaN,1,1,...,NaN,4.0,NaN,2.0,4.0,4.0,1.0,NaN,NaN,267
25,26,2015,1,1,46,4,4,NaN,2,1,...,NaN,3.0,NaN,3.0,2.0,2.0,2.0,1.0,NaN,166
26,27,2015,1,1,35,4,7,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227
27,28,2015,1,1,12,4,9,NaN,2,1,...,NaN,2.0,NaN,21.0,4.0,4.0,2.0,NaN,NaN,117
28,29,2015,1,6,46,4,12,NaN,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
29,30,2015,1,6,35,4,1,1.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102732,102733,2015,1,6,48,4,12,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480
102733,102734,2015,1,1,35,4,3,5.0,2,2,...,NaN,3.0,NaN,19.0,7.0,7.0,2.0,NaN,NaN,466
102734,102735,2015,1,1,35,4,6,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301
102735,102736,2015,1,1,35,4,3,6.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152
102736,102737,2015,1,1,35,4,3,6.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,784
102737,102738,2015,1,1,24,1,6,NaN,2,1,...,NaN,4.0,NaN,17.0,7.0,7.0,4.0,4.0,1.0,588
102738,102739,2015,1,1,24,4,7,NaN,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
102739,102740,2015,1,1,12,4,5,NaN,1,1,...,NaN,5.0,NaN,4.0,5.0,5.0,2.0,2.0,NaN,135
102740,102741,2015,1,1,10,4,10,NaN,1,1,...,NaN,4.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,109
102741,102742,2015,1,1,46,4,6,NaN,1,1,...,NaN,4.0,NaN,9.0,1.0,1.0,2.0,3.0,NaN,67
102742,102743,2015,1,1,46,4,4,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150
102743,102744,2015,1,1,24,4,8,NaN,1,2,...,NaN,5.0,NaN,NaN,NaN,NaN,0.0,5.0,1.0,523
102744,102745,2015,1,6,35,4,11,NaN,1,2,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,213
102745,102746,2015,1,4,24,1,9,NaN,1,1,...,NaN,3.0,NaN,8.0,4.0,4.0,1.0,1.0,NaN,697
102746,102747,2015,1,1,59,4,9,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450
102747,102748,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,594
102748,102749,2015,1,1,35,4,3,6.0,1,2,...,NaN,1.0,NaN,4.0,3.0,3.0,2.0,NaN,NaN,308
102749,102750,2015,1,1,24,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77
102750,102751,2015,1,1,12,4,7,NaN,1,2,...,NaN,4.0,NaN,13.0,2.0,2.0,2.0,6.0,NaN,112
102751,102752,2015,1,1,46,4,9,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
102752,102753,2015,1,1,48,4,9,NaN,1,1,...,NaN,2.0,NaN,4.0,5.0,5.0,2.0,NaN,NaN,490
102753,102754,2015,1,1,35,4,8,NaN,2,1,...,NaN,4.0,NaN,20.0,5.0,5.0,2.0,NaN,NaN,161
102754,102755,2015,1,6,59,4,10,NaN,2,1,...,NaN,2.0,NaN,12.0,7.0,7.0,6.0,NaN,NaN,136
102755,102756,2015,1,6,13,4,11,NaN,1,1,...,NaN,4.0,NaN,5.0,5.0,5.0,2.0,NaN,NaN,143
102756,102757,2015,1,1,46,4,11,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79
102757,102758,2015,1,6,10,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122
102758,102759,2015,1,1,59,4,9,NaN,2,1,...,NaN,1.0,NaN,2.0,5.0,5.0,4.0,NaN,NaN,50
102759,102760,2015,1,2,12,4,9,NaN,1,1,...,NaN,5.0,NaN,NaN,NaN,NaN,0.0,1.0,1.0,171
102760,102761,2015,1,1,24,4,8,NaN,1,1,...,NaN,4.0,NaN,3.0,5.0,5.0,2.0,6.0,NaN,585
102761,102762,2015,1,4,12,4,8,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168

In [6]:
lfs_jan["SEX"] = lfs_jan["SEX"].astype("category")

In [7]:
lfs_jan["SEX"]

0         2
1         1
2         1
3         1
4         1
5         2
6         1
7         1
8         1
9         2
10        1
11        2
12        2
13        2
14        2
15        2
16        2
17        2
18        1
19        2
20        2
21        2
22        2
23        2
24        1
25        2
26        2
27        2
28        1
29        2
         ..
102732    2
102733    2
102734    1
102735    1
102736    1
102737    2
102738    1
102739    1
102740    1
102741    1
102742    2
102743    1
102744    1
102745    1
102746    2
102747    1
102748    1
102749    2
102750    1
102751    2
102752    1
102753    2
102754    2
102755    1
102756    1
102757    2
102758    2
102759    1
102760    1
102761    1
Name: SEX, Length: 102762, dtype: category
Categories (2, int64): [1, 2]

In [8]:
lfs_jan[lfs_jan["SEX"]==1]["SEX"]

1         1
2         1
3         1
4         1
6         1
7         1
8         1
10        1
18        1
24        1
28        1
30        1
31        1
32        1
34        1
36        1
38        1
40        1
41        1
43        1
45        1
46        1
52        1
53        1
54        1
55        1
57        1
60        1
61        1
64        1
         ..
102713    1
102714    1
102717    1
102718    1
102720    1
102721    1
102723    1
102724    1
102726    1
102727    1
102728    1
102734    1
102735    1
102736    1
102738    1
102739    1
102740    1
102741    1
102743    1
102744    1
102745    1
102747    1
102748    1
102750    1
102752    1
102755    1
102756    1
102759    1
102760    1
102761    1
Name: SEX, Length: 49838, dtype: category
Categories (2, int64): [1, 2]

In [9]:
lfs_jan= lfs_jan[lfs_jan['LFSSTAT']==1]

In [10]:
lfs_jan_employ=lfs_jan

In [11]:
lfs_jan.count()

REC_NUM       55825
SURVYEAR      55825
SURVMNTH      55825
LFSSTAT       55825
PROV          55825
CMA           55825
AGE_12        55825
AGE_6         12448
SEX           55825
MARSTAT       55825
ED76to89          0
EDUC90        55825
MJH           55825
EVERWORK          0
FTPTLAST          0
COWMAIN       55825
NAICS_18      55825
NAICS_43      55825
SOC80_49          0
SOC80_21          0
NOCS_01_25    55825
NOCS_01_47    55825
YABSENT           0
WKSAWAY           0
PAYAWAY           0
UHRSMAIN      55825
AHRSMAIN      55825
FTPTMAIN      55825
UTOTHRS       55825
ATOTHRS       55825
              ...
DURJLESS          0
AVAILABL          0
LKPUBAG           0
LKEMPLOY          0
LKRELS            0
LKATADS           0
LKANSADS          0
LKOTHER           0
PRIORACT          0
YNOLKOLD          0
YNOLOOK           0
TLOLOOK           0
SCHOOLN       53425
RELREFN       55825
EFAMTYPE      55825
EFAMSIZE      55825
EFAMEMPL      55825
EFAMUNEM      55825
SP_AGE        34506
SP_LFSST      34506
SPED7689          0
SPED1990      34506
SP_SOC80          0
SP_NOCS01     29432
SP_UHRSM      27411
SP_UHRST      27411
SP_COWM       34506
AGYOWNKN      21522
SCH1624        6526
FWEIGHT       55825
Length: 79, dtype: int64

In [12]:
lfs_jan_employ.count()

REC_NUM       55825
SURVYEAR      55825
SURVMNTH      55825
LFSSTAT       55825
PROV          55825
CMA           55825
AGE_12        55825
AGE_6         12448
SEX           55825
MARSTAT       55825
ED76to89          0
EDUC90        55825
MJH           55825
EVERWORK          0
FTPTLAST          0
COWMAIN       55825
NAICS_18      55825
NAICS_43      55825
SOC80_49          0
SOC80_21          0
NOCS_01_25    55825
NOCS_01_47    55825
YABSENT           0
WKSAWAY           0
PAYAWAY           0
UHRSMAIN      55825
AHRSMAIN      55825
FTPTMAIN      55825
UTOTHRS       55825
ATOTHRS       55825
              ...
DURJLESS          0
AVAILABL          0
LKPUBAG           0
LKEMPLOY          0
LKRELS            0
LKATADS           0
LKANSADS          0
LKOTHER           0
PRIORACT          0
YNOLKOLD          0
YNOLOOK           0
TLOLOOK           0
SCHOOLN       53425
RELREFN       55825
EFAMTYPE      55825
EFAMSIZE      55825
EFAMEMPL      55825
EFAMUNEM      55825
SP_AGE        34506
SP_LFSST      34506
SPED7689          0
SPED1990      34506
SP_SOC80          0
SP_NOCS01     29432
SP_UHRSM      27411
SP_UHRST      27411
SP_COWM       34506
AGYOWNKN      21522
SCH1624        6526
FWEIGHT       55825
Length: 79, dtype: int64

In [13]:
lfs_jan["HRLYEARN"].describe()

count    47548.000000
mean        24.435641
std         12.676344
min          2.310000
25%         15.000000
50%         21.085000
75%         31.000000
max        144.510000
Name: HRLYEARN, dtype: float64

In [14]:
lfs_jan_employ["HRLYEARN"].describe()

count    47548.000000
mean        24.435641
std         12.676344
min          2.310000
25%         15.000000
50%         21.085000
75%         31.000000
max        144.510000
Name: HRLYEARN, dtype: float64

In [15]:
lfs_jan[lfs_jan['SEX']==1]['HRLYEARN'].describe()

count    23837.000000
mean        26.390003
std         13.432284
min          2.310000
25%         16.150000
50%         23.500000
75%         33.650000
max        144.510000
Name: HRLYEARN, dtype: float64

In [16]:
lfs_jan[lfs_jan['SEX']==2]['HRLYEARN'].describe()

count    23711.000000
mean        22.470894
std         11.539266
min          3.080000
25%         13.415000
50%         19.780000
75%         28.000000
max        105.770000
Name: HRLYEARN, dtype: float64

In [17]:
male_employ_wage=lfs_jan_employ[lfs_jan['SEX']==1]['HRLYEARN']
#male_employ_wage.dropna()

In [18]:
female_employ_wage=lfs_jan_employ[lfs_jan['SEX']==2]['HRLYEARN']

female_employ_wage.dropna().tolist()

[11.0,
 18.0,
 28.0,
 26.44,
 55.29,
 12.5,
 11.0,
 50.48,
 21.0,
 20.0,
 34.62,
 25.0,
 36.06,
 20.0,
 11.5,
 20.0,
 15.5,
 14.0,
 10.5,
 28.85,
 24.24,
 16.0,
 14.0,
 11.0,
 10.75,
 32.31,
 32.69,
 10.9,
 22.0,
 33.65,
 26.0,
 19.0,
 23.31,
 11.0,
 34.6,
 24.04,
 18.0,
 12.75,
 52.0,
 10.25,
 20.0,
 11.0,
 11.5,
 3.33,
 13.9,
 12.6,
 20.87,
 35.29,
 25.5,
 13.0,
 30.0,
 14.19,
 17.0,
 23.0,
 12.0,
 12.0,
 10.75,
 24.79,
 12.0,
 19.23,
 28.0,
 35.9,
 11.0,
 16.5,
 14.18,
 11.77,
 19.6,
 29.57,
 18.38,
 15.75,
 18.0,
 36.26,
 36.0,
 15.87,
 12.0,
 10.5,
 16.0,
 20.19,
 10.25,
 23.0,
 19.23,
 24.18,
 15.0,
 38.46,
 18.67,
 23.08,
 23.0,
 12.25,
 39.0,
 25.5,
 28.0,
 15.0,
 23.0,
 10.75,
 28.0,
 18.0,
 32.18,
 10.35,
 31.0,
 19.93,
 29.28,
 22.55,
 12.02,
 11.0,
 17.9,
 23.08,
 20.0,
 14.87,
 21.32,
 16.61,
 27.0,
 11.75,
 13.0,
 20.78,
 12.0,
 10.75,
 21.0,
 20.0,
 40.0,
 18.13,
 22.0,
 20.73,
 13.5,
 40.0,
 23.08,
 16.0,
 11.86,
 14.0,
 35.38,
 11.75,
 11.87,
 25.0,
 20.49,
 21.0,
 14.3,
 28.85,
 39.9,
 20.0,
 39.84,
 17.0,
 28.85,
 10.67,
 23.0,
 12.0,
 41.48,
 45.05,
 24.04,
 24.0,
 14.26,
 16.0,
 11.15,
 15.0,
 25.0,
 17.5,
 18.75,
 30.05,
 10.25,
 49.63,
 22.0,
 43.27,
 26.32,
 11.5,
 19.94,
 24.73,
 40.47,
 28.0,
 45.0,
 17.25,
 13.0,
 15.0,
 10.0,
 25.0,
 38.46,
 23.64,
 22.0,
 11.85,
 27.69,
 24.0,
 53.0,
 30.0,
 10.0,
 11.0,
 23.0,
 22.6,
 21.63,
 10.35,
 18.42,
 18.0,
 28.21,
 7.5,
 13.53,
 16.06,
 12.0,
 10.25,
 11.0,
 21.55,
 10.25,
 28.04,
 15.0,
 10.35,
 31.0,
 25.95,
 11.45,
 21.0,
 10.3,
 51.87,
 26.0,
 11.0,
 14.0,
 13.5,
 20.0,
 32.18,
 17.14,
 10.0,
 20.0,
 11.0,
 15.27,
 32.82,
 17.0,
 28.0,
 18.92,
 14.5,
 21.37,
 11.0,
 30.27,
 68.68,
 23.17,
 30.25,
 22.0,
 11.0,
 25.22,
 34.62,
 24.62,
 13.64,
 20.0,
 18.0,
 27.0,
 15.0,
 20.0,
 12.0,
 14.0,
 23.86,
 18.0,
 49.04,
 20.0,
 50.86,
 12.0,
 11.75,
 28.89,
 21.0,
 29.81,
 28.85,
 14.5,
 22.31,
 14.0,
 30.0,
 20.19,
 12.5,
 31.25,
 24.73,
 11.75,
 15.0,
 17.58,
 19.61,
 16.2,
 20.0,
 28.7,
 11.0,
 14.0,
 11.0,
 17.5,
 25.84,
 23.64,
 22.0,
 11.0,
 20.0,
 11.0,
 45.1,
 35.9,
 16.48,
 18.48,
 11.0,
 30.77,
 17.5,
 17.8,
 22.97,
 15.0,
 10.75,
 25.0,
 35.9,
 28.0,
 21.03,
 24.0,
 12.75,
 24.06,
 40.0,
 38.0,
 12.02,
 10.25,
 10.4,
 16.65,
 26.44,
 14.5,
 22.0,
 17.0,
 12.0,
 14.65,
 30.26,
 18.0,
 15.0,
 19.69,
 25.48,
 25.0,
 17.0,
 20.0,
 11.0,
 20.45,
 20.0,
 62.5,
 33.33,
 24.95,
 52.88,
 18.5,
 23.0,
 54.67,
 20.0,
 28.85,
 14.5,
 29.81,
 45.07,
 11.0,
 27.69,
 16.0,
 24.0,
 22.0,
 34.0,
 12.5,
 19.9,
 28.0,
 39.29,
 19.04,
 29.11,
 23.64,
 30.26,
 11.0,
 23.08,
 36.0,
 10.4,
 14.0,
 12.0,
 29.74,
 18.0,
 22.0,
 14.5,
 37.0,
 20.0,
 20.19,
 13.84,
 23.08,
 24.0,
 23.0,
 10.35,
 48.7,
 29.99,
 14.0,
 10.75,
 24.23,
 17.5,
 46.0,
 17.46,
 65.64,
 11.0,
 11.0,
 13.0,
 10.75,
 29.19,
 17.69,
 31.25,
 24.04,
 11.0,
 40.0,
 14.5,
 10.2,
 31.0,
 16.0,
 25.0,
 25.0,
 17.0,
 25.0,
 13.0,
 26.0,
 14.0,
 16.0,
 27.91,
 25.0,
 20.05,
 20.0,
 27.4,
 11.0,
 11.86,
 11.0,
 17.8,
 10.3,
 14.42,
 25.0,
 11.5,
 18.25,
 25.82,
 17.25,
 11.0,
 20.0,
 20.5,
 14.94,
 56.41,
 17.45,
 10.8,
 22.0,
 18.27,
 25.0,
 22.0,
 12.25,
 11.0,
 28.85,
 40.0,
 47.12,
 28.0,
 35.0,
 11.5,
 15.42,
 40.0,
 16.41,
 31.32,
 43.45,
 24.5,
 28.2,
 35.61,
 12.25,
 39.0,
 31.25,
 41.0,
 17.0,
 10.5,
 10.6,
 21.75,
 11.0,
 37.36,
 27.0,
 43.0,
 23.75,
 16.0,
 22.0,
 20.0,
 28.85,
 14.25,
 30.15,
 33.85,
 20.0,
 52.82,
 10.75,
 20.0,
 21.93,
 11.5,
 18.06,
 22.0,
 12.35,
 14.0,
 15.38,
 19.18,
 23.0,
 10.45,
 14.0,
 33.33,
 24.04,
 35.0,
 14.0,
 14.0,
 53.85,
 14.25,
 27.0,
 12.0,
 10.25,
 16.5,
 18.0,
 54.4,
 30.77,
 13.0,
 72.0,
 22.0,
 32.42,
 18.0,
 25.64,
 11.29,
 16.5,
 15.0,
 47.18,
 14.0,
 39.9,
 20.0,
 23.33,
 18.0,
 31.0,
 30.28,
 12.0,
 46.15,
 11.25,
 19.0,
 18.75,
 20.67,
 10.5,
 25.0,
 56.0,
 13.27,
 11.4,
 26.44,
 15.0,
 15.38,
 19.0,
 37.0,
 31.25,
 22.0,
 10.25,
 41.0,
 23.06,
 12.0,
 48.08,
 42.06,
 18.0,
 55.9,
 20.06,
 35.0,
 21.5,
 15.0,
 19.0,
 16.0,
 15.0,
 16.0,
 27.0,
 35.58,
 19.23,
 48.0,
 19.8,
 10.5,
 32.05,
 14.5,
 40.0,
 25.75,
 32.5,
 32.21,
 11.0,
 18.27,
 19.0,
 12.4,
 35.0,
 37.6,
 17.44,
 42.31,
 23.0,
 12.0,
 10.35,
 16.0,
 11.0,
 43.59,
 11.0,
 12.0,
 23.93,
 15.0,
 11.25,
 15.0,
 28.57,
 22.0,
 28.0,
 25.17,
 15.2,
 10.5,
 11.0,
 11.0,
 46.0,
 12.0,
 22.5,
 25.0,
 19.46,
 21.0,
 17.0,
 10.5,
 10.75,
 34.44,
 24.0,
 11.54,
 17.0,
 16.5,
 16.0,
 15.38,
 12.0,
 16.28,
 11.0,
 14.87,
 11.3,
 28.85,
 26.67,
 31.0,
 28.85,
 36.06,
 13.0,
 19.0,
 10.0,
 29.0,
 38.46,
 30.94,
 6.77,
 22.0,
 15.0,
 12.45,
 10.0,
 19.9,
 11.87,
 11.0,
 26.79,
 11.25,
 35.0,
 14.5,
 10.25,
 29.73,
 13.5,
 20.0,
 10.5,
 16.83,
 49.56,
 24.0,
 11.0,
 10.0,
 31.19,
 17.24,
 17.0,
 16.0,
 30.14,
 11.0,
 75.96,
 17.5,
 36.92,
 18.0,
 16.0,
 21.98,
 22.0,
 11.0,
 17.0,
 12.75,
 11.0,
 10.4,
 45.07,
 25.0,
 15.87,
 19.66,
 17.5,
 15.0,
 27.56,
 25.0,
 10.4,
 18.25,
 22.0,
 36.06,
 11.0,
 14.0,
 34.0,
 27.08,
 19.0,
 22.62,
 18.0,
 10.25,
 21.54,
 45.67,
 17.0,
 33.33,
 11.77,
 11.5,
 36.0,
 10.5,
 28.0,
 19.0,
 12.2,
 25.0,
 43.75,
 14.0,
 16.5,
 40.87,
 10.2,
 21.0,
 23.0,
 11.75,
 29.0,
 11.25,
 10.65,
 21.86,
 30.0,
 15.25,
 10.5,
 11.0,
 10.75,
 27.69,
 12.0,
 19.04,
 25.38,
 22.0,
 10.75,
 34.36,
 10.35,
 10.96,
 31.0,
 20.51,
 19.23,
 11.0,
 38.69,
 17.0,
 15.0,
 18.69,
 26.41,
 16.0,
 29.74,
 22.0,
 22.0,
 20.0,
 20.0,
 17.0,
 38.9,
 11.0,
 24.0,
 43.75,
 15.0,
 10.7,
 14.0,
 50.48,
 39.73,
 32.0,
 11.0,
 16.0,
 11.0,
 44.71,
 22.0,
 19.75,
 19.33,
 32.0,
 14.0,
 27.0,
 12.0,
 27.69,
 37.0,
 29.0,
 27.0,
 14.0,
 24.73,
 23.78,
 22.84,
 19.23,
 12.5,
 29.8,
 28.85,
 16.0,
 10.25,
 55.29,
 11.0,
 13.0,
 20.0,
 26.0,
 50.0,
 15.0,
 76.92,
 11.0,
 25.0,
 19.0,
 16.0,
 23.18,
 20.0,
 18.55,
 15.0,
 22.2,
 29.0,
 15.0,
 23.0,
 17.5,
 12.19,
 40.48,
 11.5,
 23.5,
 3.21,
 10.25,
 43.96,
 10.55,
 12.0,
 57.69,
 13.75,
 31.0,
 14.5,
 17.62,
 54.95,
 22.05,
 21.0,
 20.0,
 10.4,
 10.8,
 11.0,
 25.0,
 11.0,
 25.48,
 21.0,
 11.05,
 18.0,
 27.88,
 22.0,
 39.6,
 11.36,
 11.6,
 16.0,
 12.72,
 31.0,
 29.0,
 15.5,
 13.0,
 18.0,
 23.08,
 20.0,
 48.08,
 22.5,
 48.08,
 19.55,
 21.1,
 16.0,
 24.0,
 14.33,
 28.61,
 11.18,
 35.0,
 20.43,
 10.0,
 33.0,
 17.44,
 36.92,
 27.5,
 71.43,
 23.08,
 16.0,
 13.0,
 20.09,
 22.6,
 17.63,
 14.0,
 11.25,
 18.53,
 23.0,
 27.29,
 15.0,
 20.0,
 25.0,
 24.87,
 20.0,
 13.0,
 14.42,
 18.36,
 29.0,
 34.62,
 11.75,
 20.31,
 10.5,
 28.0,
 33.0,
 12.75,
 13.0,
 44.64,
 22.76,
 16.0,
 20.0,
 11.0,
 21.63,
 11.0,
 15.0,
 16.0,
 18.88,
 14.04,
 41.03,
 10.15,
 16.25,
 36.38,
 21.0,
 10.5,
 52.88,
 21.2,
 22.93,
 11.0,
 33.33,
 12.0,
 16.0,
 36.0,
 30.59,
 22.0,
 24.18,
 10.19,
 15.5,
 45.67,
 27.88,
 13.0,
 11.0,
 10.0,
 38.46,
 17.25,
 26.54,
 27.69,
 41.83,
 14.5,
 18.36,
 12.35,
 24.0,
 11.0,
 10.75,
 10.35,
 10.7,
 10.0,
 13.5,
 20.54,
 20.18,
 15.95,
 20.42,
 25.0,
 16.0,
 11.6,
 25.38,
 48.72,
 12.83,
 17.5,
 20.0,
 17.0,
 20.0,
 19.43,
 27.88,
 15.6,
 16.87,
 13.0,
 36.06,
 19.23,
 14.5,
 38.22,
 17.5,
 13.25,
 16.0,
 12.5,
 38.46,
 17.5,
 10.75,
 15.5,
 46.77,
 17.0,
 10.25,
 11.0,
 11.7,
 25.0,
 32.0,
 22.44,
 11.0,
 35.0,
 11.33,
 13.5,
 21.0,
 40.0,
 33.0,
 36.06,
 40.87,
 18.36,
 26.0,
 20.5,
 10.75,
 41.0,
 40.0,
 19.23,
 14.0,
 17.5,
 25.5,
 19.8,
 25.0,
 44.23,
 12.0,
 38.46,
 12.0,
 27.0,
 30.96,
 15.9,
 26.15,
 27.0,
 41.54,
 11.0,
 11.0,
 15.0,
 24.75,
 13.75,
 6.2,
 11.0,
 34.07,
 48.08,
 19.52,
 33.0,
 10.5,
 21.17,
 10.5,
 25.48,
 ...]

In [19]:

stats.ttest_ind(male_employ_wage.dropna(),female_employ_wage.dropna())

Ttest_indResult(statistic=34.11736459746036, pvalue=4.570767205483238e-252)

In [20]:
stats.describe(female_employ_wage,nan_policy='omit')

DescribeResult(nobs=23711, minmax=(masked_array(data=3.08,
             mask=False,
       fill_value=1e+20), masked_array(data=105.77,
             mask=False,
       fill_value=1e+20)), mean=22.47089367803973, variance=133.1546669069153, skewness=masked_array(data=1.36935365,
             mask=False,
       fill_value=1e+20), kurtosis=2.322863933761436)

In [21]:
import statsmodels.api as sm
sm.stats.ttest_ind(male_employ_wage.dropna(),female_employ_wage.dropna())

(34.11736459746036, 4.570767205483238e-252, 47546.0)

In [22]:
stats.describe(male_employ_wage,nan_policy='omit')

DescribeResult(nobs=23837, minmax=(masked_array(data=2.31,
             mask=False,
       fill_value=1e+20), masked_array(data=144.51,
             mask=False,
       fill_value=1e+20)), mean=26.39000335612703, variance=180.42625198857743, skewness=masked_array(data=1.32509504,
             mask=False,
       fill_value=1e+20), kurtosis=2.8473455918439443)

In [23]:
stats.ttest_ind(male_employ_wage,female_employ_wage,nan_policy='omit')

Ttest_indResult(statistic=34.117364597460366, pvalue=4.570767205380661e-252)

In [24]:
lfs_jan.groupby(by='PROV')['HRLYEARN'].describe()

        count       mean        std   min    25%     50%     75%     max
PROV
10     1526.0  24.436153  13.592058  5.95  13.27  21.000  31.775  117.95
11     1224.0  21.281577  10.688829  3.85  13.00  18.360  26.000   89.94
12     2301.0  22.937727  11.245551  3.33  14.00  20.000  28.850   74.52
13     2142.0  21.483735  10.321642  3.46  13.00  19.000  27.000   76.92
24     8028.0  23.136674  11.592467  3.75  14.50  20.000  29.000   80.13
35    13624.0  24.804935  13.327961  3.13  14.50  21.390  31.790  105.77
46     4739.0  22.391068  10.799496  3.46  14.00  19.560  27.985   79.33
47     3458.0  25.893395  13.082827  2.31  16.00  22.575  33.770  100.00
48     5314.0  28.307375  14.688408  3.08  17.65  25.000  36.000  144.51
59     5192.0  25.032764  12.025007  3.13  16.00  23.000  31.855  104.62

In [25]:
lfs_jan['FWEIGHT']

0          44
2         195
4         101
5          60
7         415
8         106
9         204
10        117
11        714
12        202
14        521
16        127
18        216
20        559
21        194
22        164
23        550
24        267
25        166
26        227
27        117
32         80
35        353
38        129
41        129
43        121
45        789
46        273
47        520
51        562
         ...
102719    143
102720    451
102721    132
102722    106
102723    129
102724    871
102726    246
102730     94
102731    117
102733    466
102734    301
102735    152
102736    784
102737    588
102738     85
102739    135
102740    109
102741     67
102742    150
102743    523
102746    450
102748    308
102749     77
102750    112
102751     20
102752    490
102753    161
102756     79
102758     50
102760    585
Name: FWEIGHT, Length: 55825, dtype: int64

Find out weights

In [35]:

dummy_sex ={
    1:0,
    2:1}
x=lfs_jan['SEX'].map(dummy_sex)

y=lfs_jan['HRLYEARN']
model = sm.OLS(y,x)
results=model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               HRLYEARN   R-squared:                         nan
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Mon, 21 Jan 2019   Prob (F-statistic):                nan
Time:                        12:48:43   Log-Likelihood:                    nan
No. Observations:              102762   AIC:                               nan
Df Residuals:                  102761   BIC:                               nan
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
SEX               nan        nan        nan        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                     nan
Prob(Omnibus):                    nan   Jarque-Bera (JB):                  nan
Skew:                             nan   Prob(JB):                          nan
Kurtosis:                         nan   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [28]:
x

0         1
2         0
4         0
5         1
7         0
8         0
9         1
10        0
11        1
12        1
14        1
16        1
18        0
20        1
21        1
22        1
23        1
24        0
25        1
26        1
27        1
32        0
35        1
38        0
41        0
43        0
45        0
46        0
47        1
51        1
         ..
102719    1
102720    0
102721    0
102722    1
102723    0
102724    0
102726    0
102730    1
102731    1
102733    1
102734    0
102735    0
102736    0
102737    1
102738    0
102739    0
102740    0
102741    0
102742    1
102743    0
102746    1
102748    0
102749    1
102750    0
102751    1
102752    0
102753    1
102756    0
102758    1
102760    0
Name: SEX, Length: 55825, dtype: int64