In [1]:
import pandas as pd

In [2]:
lfs_jan = pd.read_stata("lfs_01_2015.dta")

ValueError: Version of given Stata file is not 104, 105, 108, 111 (Stata 7SE), 113 (Stata 8/9), 114 (Stata 10/11), 115 (Stata 12), 117 (Stata 13), or 118 (Stata 14)

In [3]:
lfs_jan = pd.read_table("lfs_01_2015.dta", sep= '\t')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 8, saw 3

In [4]:
lfs_jan = pd.read_table("lfs_01_2015.dta")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 8, saw 3

In [5]:
lfs_jan = pd.read_table("lfs_01_2015.tab", sep= '\t')

In [6]:
lfs_jan

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SPED7689,SPED1990,SP_SOC80,SP_NOCS01,SP_UHRSM,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT
0,1,2015,1,1,11,4,12,NaN,2,1,...,NaN,3.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,44
1,2,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,84
2,3,2015,1,1,35,4,7,NaN,1,1,...,NaN,5.0,NaN,5.0,4.0,4.0,2.0,3.0,NaN,195
3,4,2015,1,4,59,4,3,5.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110
4,5,2015,1,1,24,4,4,NaN,1,2,...,NaN,5.0,NaN,10.0,4.0,4.0,1.0,1.0,NaN,101
5,6,2015,1,1,46,4,7,NaN,2,1,...,NaN,4.0,NaN,6.0,5.0,5.0,2.0,4.0,1.0,60
6,7,2015,1,6,35,4,12,NaN,1,1,...,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,235
7,8,2015,1,1,59,3,9,NaN,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,415
8,9,2015,1,1,47,4,12,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,106
9,10,2015,1,1,35,4,11,NaN,2,1,...,NaN,2.0,NaN,23.0,NaN,NaN,1.0,NaN,NaN,204
10,11,2015,1,1,59,3,2,4.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117
11,12,2015,1,1,59,3,2,4.0,2,2,...,NaN,5.0,NaN,6.0,5.0,5.0,2.0,NaN,NaN,714
12,13,2015,1,1,35,4,8,NaN,2,1,...,NaN,2.0,NaN,24.0,5.0,5.0,2.0,NaN,NaN,202
13,14,2015,1,6,10,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84
14,15,2015,1,1,48,4,5,NaN,2,1,...,NaN,5.0,NaN,6.0,5.0,5.0,1.0,2.0,NaN,521
15,16,2015,1,6,12,4,11,NaN,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138
16,17,2015,1,1,24,4,3,5.0,2,2,...,NaN,4.0,NaN,2.0,7.0,7.0,5.0,NaN,NaN,127
17,18,2015,1,2,59,4,3,6.0,2,1,...,NaN,1.0,NaN,21.0,5.0,5.0,2.0,1.0,NaN,112
18,19,2015,1,1,35,4,8,NaN,1,1,...,NaN,4.0,NaN,14.0,1.0,3.0,2.0,4.0,1.0,216
19,20,2015,1,6,24,1,11,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,772
20,21,2015,1,1,48,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,559
21,22,2015,1,1,35,4,8,NaN,2,2,...,NaN,4.0,NaN,9.0,5.0,5.0,1.0,NaN,NaN,194
22,23,2015,1,1,47,4,6,NaN,2,1,...,NaN,4.0,NaN,17.0,5.0,5.0,2.0,5.0,1.0,164
23,24,2015,1,1,48,4,4,NaN,2,1,...,NaN,4.0,NaN,20.0,5.0,5.0,2.0,2.0,NaN,550
24,25,2015,1,1,35,4,8,NaN,1,1,...,NaN,4.0,NaN,2.0,4.0,4.0,1.0,NaN,NaN,267
25,26,2015,1,1,46,4,4,NaN,2,1,...,NaN,3.0,NaN,3.0,2.0,2.0,2.0,1.0,NaN,166
26,27,2015,1,1,35,4,7,NaN,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227
27,28,2015,1,1,12,4,9,NaN,2,1,...,NaN,2.0,NaN,21.0,4.0,4.0,2.0,NaN,NaN,117
28,29,2015,1,6,46,4,12,NaN,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
29,30,2015,1,6,35,4,1,1.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102732,102733,2015,1,6,48,4,12,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480
102733,102734,2015,1,1,35,4,3,5.0,2,2,...,NaN,3.0,NaN,19.0,7.0,7.0,2.0,NaN,NaN,466
102734,102735,2015,1,1,35,4,6,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301
102735,102736,2015,1,1,35,4,3,6.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152
102736,102737,2015,1,1,35,4,3,6.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,784
102737,102738,2015,1,1,24,1,6,NaN,2,1,...,NaN,4.0,NaN,17.0,7.0,7.0,4.0,4.0,1.0,588
102738,102739,2015,1,1,24,4,7,NaN,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
102739,102740,2015,1,1,12,4,5,NaN,1,1,...,NaN,5.0,NaN,4.0,5.0,5.0,2.0,2.0,NaN,135
102740,102741,2015,1,1,10,4,10,NaN,1,1,...,NaN,4.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,109
102741,102742,2015,1,1,46,4,6,NaN,1,1,...,NaN,4.0,NaN,9.0,1.0,1.0,2.0,3.0,NaN,67
102742,102743,2015,1,1,46,4,4,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150
102743,102744,2015,1,1,24,4,8,NaN,1,2,...,NaN,5.0,NaN,NaN,NaN,NaN,0.0,5.0,1.0,523
102744,102745,2015,1,6,35,4,11,NaN,1,2,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,213
102745,102746,2015,1,4,24,1,9,NaN,1,1,...,NaN,3.0,NaN,8.0,4.0,4.0,1.0,1.0,NaN,697
102746,102747,2015,1,1,59,4,9,NaN,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450
102747,102748,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,594
102748,102749,2015,1,1,35,4,3,6.0,1,2,...,NaN,1.0,NaN,4.0,3.0,3.0,2.0,NaN,NaN,308
102749,102750,2015,1,1,24,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77
102750,102751,2015,1,1,12,4,7,NaN,1,2,...,NaN,4.0,NaN,13.0,2.0,2.0,2.0,6.0,NaN,112
102751,102752,2015,1,1,46,4,9,NaN,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
102752,102753,2015,1,1,48,4,9,NaN,1,1,...,NaN,2.0,NaN,4.0,5.0,5.0,2.0,NaN,NaN,490
102753,102754,2015,1,1,35,4,8,NaN,2,1,...,NaN,4.0,NaN,20.0,5.0,5.0,2.0,NaN,NaN,161
102754,102755,2015,1,6,59,4,10,NaN,2,1,...,NaN,2.0,NaN,12.0,7.0,7.0,6.0,NaN,NaN,136
102755,102756,2015,1,6,13,4,11,NaN,1,1,...,NaN,4.0,NaN,5.0,5.0,5.0,2.0,NaN,NaN,143
102756,102757,2015,1,1,46,4,11,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79
102757,102758,2015,1,6,10,4,1,2.0,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122
102758,102759,2015,1,1,59,4,9,NaN,2,1,...,NaN,1.0,NaN,2.0,5.0,5.0,4.0,NaN,NaN,50
102759,102760,2015,1,2,12,4,9,NaN,1,1,...,NaN,5.0,NaN,NaN,NaN,NaN,0.0,1.0,1.0,171
102760,102761,2015,1,1,24,4,8,NaN,1,1,...,NaN,4.0,NaN,3.0,5.0,5.0,2.0,6.0,NaN,585
102761,102762,2015,1,4,12,4,8,NaN,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168

In [7]:
lfs_jan.describe()

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SPED7689,SPED1990,SP_SOC80,SP_NOCS01,SP_UHRSM,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT
count,102762.000000,102762.0,102762.0,102762.000000,102762.000000,102762.000000,102762.000000,22414.000000,102762.000000,102762.000000,...,0.0,58596.000000,0.0,40991.000000,37358.000000,37358.000000,58596.000000,28912.000000,8401.0,102762.00000
mean,51381.500000,2015.0,1.0,3.014159,35.203918,3.717493,6.932679,3.590524,1.515015,2.854820,...,NaN,3.280036,NaN,11.818668,4.371728,4.452808,1.565533,3.266637,1.0,283.56011
std,29664.978518,0.0,0.0,2.358880,14.603083,0.757273,3.506167,1.693034,0.499777,2.158683,...,NaN,1.502246,NaN,7.109661,1.501815,1.520393,1.518121,1.745424,0.0,252.68946
min,1.000000,2015.0,1.0,1.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,0.000000,NaN,1.000000,1.000000,1.000000,0.000000,1.000000,1.0,1.00000
25%,25691.250000,2015.0,1.0,1.000000,24.000000,4.000000,4.000000,2.000000,1.000000,1.000000,...,NaN,2.000000,NaN,5.000000,4.000000,4.000000,0.000000,2.000000,1.0,114.00000
50%,51381.500000,2015.0,1.0,1.000000,35.000000,4.000000,7.000000,4.000000,2.000000,2.000000,...,NaN,4.000000,NaN,10.000000,5.000000,5.000000,2.000000,3.000000,1.0,177.00000
75%,77071.750000,2015.0,1.0,6.000000,47.000000,4.000000,10.000000,5.000000,2.000000,6.000000,...,NaN,4.000000,NaN,18.000000,5.000000,5.000000,2.000000,5.000000,1.0,383.00000
max,102762.000000,2015.0,1.0,6.000000,59.000000,4.000000,12.000000,6.000000,2.000000,6.000000,...,NaN,5.000000,NaN,25.000000,7.000000,7.000000,7.000000,6.000000,1.0,2139.00000

In [8]:
lfs_jan.head()

,REC_NUM,SURVYEAR,SURVMNTH,LFSSTAT,PROV,CMA,AGE_12,AGE_6,SEX,MARSTAT,...,SPED7689,SPED1990,SP_SOC80,SP_NOCS01,SP_UHRSM,SP_UHRST,SP_COWM,AGYOWNKN,SCH1624,FWEIGHT
0,1,2015,1,1,11,4,12,NaN,2,1,...,NaN,3.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,44
1,2,2015,1,6,24,4,11,NaN,1,1,...,NaN,2.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,84
2,3,2015,1,1,35,4,7,NaN,1,1,...,NaN,5.0,NaN,5.0,4.0,4.0,2.0,3.0,NaN,195
3,4,2015,1,4,59,4,3,5.0,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110
4,5,2015,1,1,24,4,4,NaN,1,2,...,NaN,5.0,NaN,10.0,4.0,4.0,1.0,1.0,NaN,101

In [9]:
lfs_jan['HRLYEARN'].describe()

count    50968.000000
mean        24.438470
std         12.623649
min          2.310000
25%         15.000000
50%         21.150000
75%         31.000000
max        144.510000
Name: HRLYEARN, dtype: float64

In [14]:
lfs_jan[lfs_jan['SEX']==1]['HRLYEARN'].describe()

count    25075.000000
mean        26.408024
std         13.400958
min          2.310000
25%         16.250000
50%         23.500000
75%         33.815000
max        144.510000
Name: HRLYEARN, dtype: float64

In [15]:
lfs_jan[lfs_jan['SEX']==2]['HRLYEARN'].describe()

count    25893.000000
mean        22.531139
std         11.505556
min          3.080000
25%         13.500000
50%         19.950000
75%         28.000000
max        105.770000
Name: HRLYEARN, dtype: float64

In [16]:
list(lfs_jan)

['REC_NUM',
 'SURVYEAR',
 'SURVMNTH',
 'LFSSTAT',
 'PROV',
 'CMA',
 'AGE_12',
 'AGE_6',
 'SEX',
 'MARSTAT',
 'ED76to89',
 'EDUC90',
 'MJH',
 'EVERWORK',
 'FTPTLAST',
 'COWMAIN',
 'NAICS_18',
 'NAICS_43',
 'SOC80_49',
 'SOC80_21',
 'NOCS_01_25',
 'NOCS_01_47',
 'YABSENT',
 'WKSAWAY',
 'PAYAWAY',
 'UHRSMAIN',
 'AHRSMAIN',
 'FTPTMAIN',
 'UTOTHRS',
 'ATOTHRS',
 'HRSAWAY',
 'YAWAY',
 'PAIDOT',
 'UNPAIDOT',
 'XTRAHRS',
 'WHYPTOLD',
 'WHYPTNEW',
 'TENURE',
 'PREVTEN',
 'HRLYEARN',
 'UNION',
 'PERMTEMP',
 'ESTSIZE',
 'FIRMSIZE',
 'DURUNEMP',
 'FLOWUNEM',
 'UNEMFTPT',
 'WHYLEFTO',
 'WHYLEFTN',
 'DURJLESS',
 'AVAILABL',
 'LKPUBAG',
 'LKEMPLOY',
 'LKRELS',
 'LKATADS',
 'LKANSADS',
 'LKOTHER',
 'PRIORACT',
 'YNOLKOLD',
 'YNOLOOK',
 'TLOLOOK',
 'SCHOOLN',
 'RELREFN',
 'EFAMTYPE',
 'EFAMSIZE',
 'EFAMEMPL',
 'EFAMUNEM',
 'SP_AGE',
 'SP_LFSST',
 'SPED7689',
 'SPED1990',
 'SP_SOC80',
 'SP_NOCS01',
 'SP_UHRSM',
 'SP_UHRST',
 'SP_COWM',
 'AGYOWNKN',
 'SCH1624',
 'FWEIGHT']